export const LABELS = {
  PROJECT_NAME: 'Inboxly',
  EMAIL_PLACHOLDER: 'Inboxly Email Address*',
  USERNAME: 'Username*',
  PASSWORD_PLACHOLDER: 'Password*',
  MOBILE_PLACHOLDER: 'ENTER YOUR MOBILE NO.*',
  USERNAME_PLACHOLDER: 'ENTER YOUR USERNAME*',
  LOGIN: 'LOGIN',
  EMAILDATA: 'Your personal email address',
  LOGIN_HEAD: 'Login to your account!',
  RESISTER: 'RESISTER',
  ALREADY_ACCOUNT: 'ALREADY HAVE AN ACCOUNT?',
  FORGOT_PASSWORD: 'Forgot Password?',
  NEED_RESISTER: 'Do not have an account?',
  CREATE_NOW: ' Create now',
  ADD_CATEGORY: 'Add Category',
  ADD_CATEGORY_MSG: 'Please enter the category name',
  LOGIN_ERROR:
    'ERROR: The email and password combination you does not appear to match any in our system',
  SIGNUP_ERROR: 'ERROR: Please enter all the required fields',
  SIGNUP_HEAD: 'Create your account on Inboxly!',
  LABLE_NAME: 'Name*',
  SIGNUP_LABLE_EMAIL: 'Create your Inboxly Email*',
  CREATE_ACCOUNT_BUTTON: 'CREATE ACCOUNT',
  SIGNUP_LABLE_RECOVERY_EMAIL: 'Recovery Email Address*',
  SIGNUP_BUTTON_BACK_LOGIN: 'Back to Login',
  BACK: 'Back',
  FORGOT_PASSWORD_HEAD: 'Please enter your recovery email address to receive reset password code',
  RECOVER_EMAIL_LABLE: 'Recovery Email Address*',
  RECOVER_SEND_CODE: 'SEND CODE',
  VERIFY_EMAIL_OTP_HEAD: 'Please enter verification code received on your recovery email address',
  VERIFY_EMAIL_OTP_LABLE: 'Verification Code',
  VERIFY_OTP_BUTTON: 'VERIFY',
  RESEND_OTP_BUTTON: 'Resend Code',
  UPDATE_PROFILE_NAME_LABLE: 'Name*',
  UPDATE_PROFILE_INBOXLY_EMAIL_LABLE: 'Inboxly Email Address',
  UPDATE_PROFILE_RECOVERY_EMAIL_LABLE: 'Recovery Email Address*',
  UPDATE_PROFILE_DETAILS_BUTTON: 'UPDATE DETAILS',
  CHANGE_PWD_CURRENT_PASSWORD: 'Current Password*',
  CHANGE_PWD_NEW_PASSWORD: 'New Password*',
  CHANGE_PWD_CONFIRM_PASSWORD: 'Confirm New Password*',
  UPDATE_PASSWORD_BUTTON: 'UPDATE PASSWORD',
  DELETE_ACCOUNT_HEAD: 'Are you sure you want to delete this account? Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  DELETE_ACCOUNT_NO_BUTTON: 'NO, CANCEL',
  DELETE_ACCOUNT_YES_BUTTON: 'YES, DELETE',
  AUTO_DELETE_NEWS_HEAD: 'Select when unsaved emails are automatically deleted.',
  AUTO_DELETE_NEWS_UPDATE_BUTTON: 'UPDATE ',
  SEARCH: 'Search Inbox',
  SEARCH_SENDER: 'Search News Sender',
  CANCEL: 'Cancel',
  OK: 'OK',
  INFOEMAIL: '(This can not be changed)',
  ADD: 'Add',
  UPDATE: 'Update', 
  NOTIFICATIONS: 'Notifications',
  NO_DATA: 'No data found',
  WELCOME  :'Welcome to Inboxly!',
  WELCOME_MESSAGE:'Your inbox has been set up. You can now create categories and start subscribing to newsletters!',
  EDIT_CATEGORY: 'Edit Category',
  CHANGE_CATEGORY: 'Change Category',
  ASSIGN_CATEGORY: 'Assign Category',
  SNOOZE_SENDER: 'Snooze Sender',
  SNOOZED_SENDER: 'Snoozed Senders',
  UNSNOOZED_SENDER: 'Unsnooze Sender',
  SNOOZE: 'Snooze',
  REMOVE: 'Remove',
  NEWS_SENDERS: 'News Senders',
  SAVE_NEWS: 'Save',
  ARCHIVE_NEWS: 'Archive',
  DELETE_NEWS: 'Delete',
  UNSAVE:'Unsave',
  INBOX: 'Inbox',
  MANAGE_CATEGORY: 'Inbox Categories',
  MANAGE_SENDER: 'View Senders',
  SAVED_EMAIL: 'Saved Emails',
  ARCHIVE_EMAIL: 'Archived Emails',
  ACCOUNT_SETTINGS: 'Account Settings',
  RATE_US: 'Rate Us',
  LOGOUT: 'Logout',
  LEGEL: 'Legal',
  MANAGE_NOTIFICATIONS : 'Manage Notifications',
  MANAGE_PROFILE: 'Manage Profile',
  DELETE_ACCOUNT: 'Delete Account',
  CHANGE_PASSWORD: 'Change Password',
  AUTO_DELETE_NEWS: 'Manage Auto Delete',
  AUTO_DELETE: 'Auto Delete Email Settings',
  PRIVACY: 'Privacy Policy',
  DONE: 'Done',
  ALERT: 'Alert',
  ACCOUNT_DELETE_ALERT: 'Are you sure you want to delete your account?',
  DELETE_MSG: 'When you delete your account, your Inboxly email address will be reset and can be claimed by any user.',
  DELETE_INFO: 'All of your saved emails, data and history will be deleted.',
  DELETE_NOTE: ' Uninstalling the App without deleting your account will not delete your account or data.',
  UNREAD_EMAILS: 'Unread Emails',
  NEW_TO_OLD_EMAILS: 'New to Old Emails',
  READ_EMAILS: 'Read Emails',
  OLD_TO_NEW_EMAILS: 'Old to New Emails',
};