require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'inboxly' do
  pod 'Firebase/Crashlytics'

  # Recommended: Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  target 'inboxlyTests' do
    inherit! :complete
    # Pods for testing
  end 

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.80.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'inboxly-tvOS' do
  # Pods for inboxly-tvOS

  target 'inboxly-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
